if imag(RpM(i,j))~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(HT/R1/v1)~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(acosd((pT-R0)/(R0*eT)))~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(acosd((pT-R1)/(R1*eT)))~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(vM/v2*cosd(lambda1(j))-v1SI/v2*cosd(lambda1(j)+gamma1-phi1))~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(phi1-gamma1)~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(lambda1(j)+gamma1-phi1)~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif imag(eps2)~=0
    RpM(i,j)=0;
    vpM(i,j)=0;
elseif eps2<=0
    RpM(i,j)=0;
    vpM(i,j)=0;
end